BCRM.BXH.ThaiLand/Controllers/CommonController.cs
using BCRM.BXH.ThaiLand.Filter;
using BCRM.BXH.ThaiLand.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BCRM.BXH.ThaiLand.Controllers
{
    public class CommonController : BaseController
    {
        [Localization]
        public ActionResult Header()
        {
            return View(UserContext);
        }
        [Localization]
        public ActionResult EmptyHeader()
        {
            return View();
        }
        [Localization]
        public ActionResult Paging(Pager pager)
        {
            return View(pager);
        }
        [Localization]
        public ActionResult ErrorPage(HandleErrorInfo err)
        {
            return View(err);
        }
    }
}

BCRM.BXH.ThaiLand/Views/Shared/_Layout.cshtml
@{
    var version = System.Configuration.ConfigurationManager.AppSettings["Version"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>BCRM.BXH.Thailand</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/bootstrap/css/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/css/style-metro.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/css/style.css?v=@version" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/css/style-responsive.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/css/themes/default.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/uniform/css/uniform.default.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/select2/select2_metro.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/data-tables/DT_bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/chosen-bootstrap/chosen/chosen.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/bootstrap-tree/bootstrap-tree/css/bootstrap-tree.css" />
    <link rel="stylesheet" type="text/css" href="/Content/assets/plugins/glyphicons/css/glyphicons.css" />
    <link rel="stylesheet" type="text/css" href="/Content/Css/Common.css?v=@version" />
    <link rel="shortcut icon" href="/Content/assets/img/bcrm-icon.ico?v=@version" />
    <script type="text/javascript">
        var sysversion = '@version';
    </script>
</head>
<body>
    @Html.Action("Header", "Common")
    <div class="page-container row-fluid full-width-page fixed-top">
        <div class="page-content no-min-height" id="divPageContent">
            <div class="container-fluid" id="main-content">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderPage("~/Views/Common/Footer.cshtml")
    @RenderPage("~/Views/Common/Dialogs.cshtml")
    <script type="text/javascript" src="/Content/assets/plugins/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery.blockui.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery.cookie.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery.form.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/uniform/jquery.uniform.min.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/bootstrap-tree/bootstrap-tree/js/bootstrap-tree.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/chosen-bootstrap/chosen/chosen.jquery.js"></script>
    <script type="text/javascript" src="/Content/assets/plugins/breakpoints/breakpoints.js"></script>
    <script type="text/javascript" src="/Content/assets/scripts/head.min.js"></script>
    <script type="text/javascript" src="/Content/assets/scripts/json.js"></script>
    <script type="text/javascript" src="/Content/assets/scripts/app.js?v=@version"></script>
    <script type="text/javascript" src="~/Content/assets/scripts/dialog.js?v=@version"></script>
    <script type="text/javascript" src="/Content/assets/scripts/jsondata.js?v=@version"></script>
    <script type="text/javascript" src="/Content/assets/scripts/bcrm.library.js?v=@version"></script>
    <script type="text/javascript" src="/Content/assets/scripts/dialog.js?v=@version"></script>
    @RenderSection("Script", false)
</body>
</html>